### ISSUE TITLE
createComponent & createContext should not log anything on their own

### ISSUE THREAD

**Issue by antoniom** [grigorischristainas/react-add-new#5]
Provided that #3 is resolved, logging should be removed from both functions.
If the succeeds it could return `true`. When the function fails, just throw the error. The caller should be able to handle that error.

**Comment by grigorischristainas** [comment]
@antoniom thanks for the suggestion, I removed logging from these utils. They now return a result of the following `CreateStatus` type:
```ts
type CreateStatus = {
    status: 'OK' | 'ERR'
    msg: string
}
```

**Comment by antoniom** [comment]
Thanks @grigorischristainas !
